name: Basic Workflow develop

#trigger
on:
    push:
       branches:
           - main
#push on main branch


jobs:
    run-unit-test-job:
        runs-on: ubuntu-latest
        steps:
            - name: clone source code to runner
              uses: actions/checkout@v5

            - name: install dependencies
              run: npm i

            - name: run unit test
              run: npm run test

    build-docker-image-and-push:
        runs-on: ubuntu-latest
        needs: run-unit-test-job
        steps:
            - name: clone source code to runner
              uses: actions/checkout@v5

            - name: build docker image
              run: docker build -t salhimariam/api-sessionn13 .
            
            - name: tag docker image with version
              run: docker tag salhimariam/api-sessionn13 salhimariam/api-sessionn13:v${{ github.run_number}}

            - run: docker images

            - run: echo ${{ vars.DOCKERHUB_USERNAME }}
            - run: echo ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                    username: ${{ vars.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: push docker image
              run: docker push salhimariam/api-sessionn13:v${{ github.run_number}}
            
            - name: push docker image with version latest
              run: docker push salhimariam/api-sessionn13:latest
                   

   #3 deploy to vps
      # - ssh connection
      # - pull docker image
      # - run docker container