name: Basic Workflow develop

#trigger
on:
    push:
       branches:
           - main
#push on main branch


jobs:
    run-unit-test-job:
        runs-on: ubuntu-latest
        steps:
            - name: clone source code to runner
              uses: actions/checkout@v5

            - name: install dependencies
              run: npm i

            - name: run unit test
              run: npm run test

    build-docker-image-and-push:
        runs-on: ubuntu-latest
        needs: run-unit-test-job
        steps:
            - name: clone source code to runner
              uses: actions/checkout@v5

            - name: build docker image
              run: docker build -t salhimariam/api-sessionn13 .
            - run: docker images
            
      # - build docker image
      # - tag docker image with version
      # - login to dockerhub
      # - push docker image
      
   #3 deploy to vps
      # - ssh connection
      # - pull docker image
      # - run docker container